export const cardsList = [
  {
    name: "SBI Cashback",
    id: "sbiCashback",
  },
  {
    name: "ICICI Sapphiro",
    id: "iciciSapphiro",
  },
  {
    name: "Axis Atlas",
    id: "axisAtlas",
  },
  {
    name: "One Card",
    id: "oneCard",
  },
  {
    name: "HDFC TATA Neu Infinity",
    id: "hdfcTataNeuInfinity",
  },
  {
    name: "HSBC Cashback",
    id: "hsbcCashback",
  },
  {
    name: "HDFC Millennia",
    id: "hdfcMillennia",
  },
];

export const cardsDetails = {
  sbiCashback: [
    { annualFees: "₹999" },
    { joiningBenefits: "" },
    { renewalBenefits: "" },
    { baseRewardRate: "5%" },
    { domesticLoungeAccess: "0" },
    { internationalLoungeAccess: "0" },
    { BREAK: "" },
    { education: "0%", multiplier: 0, cap: null },
    { fuel: "0%", multiplier: 0, cap: null },
    { jewellery: "0%", multiplier: 0, cap: null },
    { govtPayments: "0%", multiplier: 0, cap: null },
    { insurance: "0%", multiplier: 0 },
    { offlineSpends: "1%", multiplier: 0.01, cap: null },
    { onlineSpends: "5%", multiplier: 0.05, cap: null },
    { rent: "0%", multiplier: 0 },
    { utilities: "0%", multiplier: 0 },
    { wallet: "0%", multiplier: 0 },
    { BREAK: "" },
    { swiggy: "5%", multiplier: 0.05, cap: null },
    { zomato: "5%", multiplier: 0.05, cap: null },
    { uber: "5%", multiplier: 0.05, cap: null },
    { ola: "5%", multiplier: 0.05, cap: null },
    { amazon: "5%", multiplier: 0.05, cap: null },
    { flipkart: "5%", multiplier: 0.05, cap: null },
    { bestFor: "Online Spends" },
  ],
  iciciSapphiro: [
    { annualFees: "₹" },
    { joiningBenefits: "" },
    { renewalBenefits: "" },
    { baseRewardRate: "1%" },
    { domesticLoungeAccess: "" },
    { internationalLoungeAccess: "" },
    { BREAK: "" },
    { education: "23", multiplier: 0 },
    { fuel: "54", multiplier: 0 },
    { jewellery: "465", multiplier: 0 },
    { govtPayments: "46", multiplier: 0 },
    { insurance: "425", multiplier: 0 },
    { offlineSpends: "46", multiplier: 0 },
    { onlineSpends: "36", multiplier: 0 },
    { rent: "35", multiplier: 0 },
    { utilities: "53", multiplier: 0 },
    { wallet: "536", multiplier: 0 },
    { BREAK: "" },
    { swiggy: "356", multiplier: 0 },
    { zomato: "536", multiplier: 0 },
    { uber: "34", multiplier: 0 },
    { ola: "36", multiplier: 0 },
    { amazon: "56", multiplier: 0 },
    { flipkart: "356", multiplier: 0 },
    { bestFor: "234", multiplier: 0 },
  ],
  axisAtlas: [
    { annualFees: "₹" },
    { joiningBenefits: "" },
    { renewalBenefits: "" },
    { baseRewardRate: "1%" },
    { domesticLoungeAccess: "" },
    { internationalLoungeAccess: "" },
    { BREAK: "" },
    { education: "23", multiplier: 0 },
    { fuel: "54", multiplier: 0 },
    { jewellery: "465", multiplier: 0 },
    { govtPayments: "46", multiplier: 0 },
    { insurance: "425", multiplier: 0 },
    { offlineSpends: "46", multiplier: 0 },
    { onlineSpends: "36", multiplier: 0 },
    { rent: "35", multiplier: 0 },
    { utilities: "53", multiplier: 0 },
    { wallet: "536", multiplier: 0 },
    { BREAK: "" },
    { swiggy: "356", multiplier: 0 },
    { zomato: "536", multiplier: 0 },
    { uber: "34", multiplier: 0 },
    { ola: "36", multiplier: 0 },
    { amazon: "56", multiplier: 0 },
    { flipkart: "356", multiplier: 0 },
    { bestFor: "234", multiplier: 0 },
  ],
  tataNeuPlus: [
    { annualFees: "₹" },
    { joiningBenefits: "" },
    { renewalBenefits: "" },
    { baseRewardRate: "1%" },
    { domesticLoungeAccess: "" },
    { internationalLoungeAccess: "" },
    { BREAK: "" },
    { education: "23", multiplier: 0 },
    { fuel: "54", multiplier: 0 },
    { jewellery: "465", multiplier: 0 },
    { govtPayments: "46", multiplier: 0 },
    { insurance: "425", multiplier: 0 },
    { offlineSpends: "46", multiplier: 0 },
    { onlineSpends: "36", multiplier: 0 },
    { rent: "35", multiplier: 0 },
    { utilities: "53", multiplier: 0 },
    { wallet: "536", multiplier: 0 },
    { BREAK: "" },
    { swiggy: "356", multiplier: 0 },
    { zomato: "536", multiplier: 0 },
    { uber: "34", multiplier: 0 },
    { ola: "36", multiplier: 0 },
    { amazon: "56", multiplier: 0 },
    { flipkart: "356", multiplier: 0 },
    { bestFor: "234", multiplier: 0 },
  ],
  oneCard: [
    { annualFees: "₹" },
    { joiningBenefits: "" },
    { renewalBenefits: "" },
    { baseRewardRate: "1%" },
    { domesticLoungeAccess: "" },
    { internationalLoungeAccess: "" },
    { BREAK: "" },
    { education: "23", multiplier: 0 },
    { fuel: "54", multiplier: 0 },
    { jewellery: "465", multiplier: 0 },
    { govtPayments: "46", multiplier: 0 },
    { insurance: "425", multiplier: 0 },
    { offlineSpends: "46", multiplier: 0 },
    { onlineSpends: "36", multiplier: 0 },
    { rent: "35", multiplier: 0 },
    { utilities: "53", multiplier: 0 },
    { wallet: "536", multiplier: 0 },
    { BREAK: "" },
    { swiggy: "356", multiplier: 0 },
    { zomato: "536", multiplier: 0 },
    { uber: "34", multiplier: 0 },
    { ola: "36", multiplier: 0 },
    { amazon: "56", multiplier: 0 },
    { flipkart: "356", multiplier: 0 },
    { bestFor: "234", multiplier: 0 },
  ],
  hdfcTataNeuInfinity: [
    { annualFees: "₹1499" },
    { joiningBenefits: "" },
    { renewalBenefits: "" },
    { baseRewardRate: "1.5%" },
    { domesticLoungeAccess: "0" },
    { internationalLoungeAccess: "0" },
    { BREAK: "" },
    { education: "1.5%", multiplier: 0.015, cap: null },
    { fuel: "0%", multiplier: 0, cap: null },
    { jewellery: "1.5%", multiplier: 0.015, cap: null },
    { govtPayments: "0%", multiplier: 0, cap: null },
    { insurance: "1.5%", multiplier: 0.015, cap: null },
    { offlineSpends: "1.5%", multiplier: 0.015, cap: null },
    { onlineSpends: "1.5%", multiplier: 0.015, cap: null },
    { rent: "0%", multiplier: 0 },
    { utilities: "1.5%", multiplier: 0.015, cap: null },
    { wallet: "0%", multiplier: 0 },
    { BREAK: "" },
    { swiggy: "1.5%", multiplier: 0.015, cap: null },
    { zomato: "1.5%", multiplier: 0.015, cap: null },
    { uber: "1.5%", multiplier: 0.015, cap: null },
    { ola: "1.5%", multiplier: 0.015, cap: null },
    { amazon: "1.5%", multiplier: 0.015, cap: null },
    { flipkart: "1.5%", multiplier: 0.015, cap: null },
    { bestFor: "Online Spends" },
  ],
  hsbcCashback: [
    { annualFees: "₹999" },
    { joiningBenefits: "" },
    { renewalBenefits: "" },
    { baseRewardRate: "5%" },
    { domesticLoungeAccess: "0" },
    { internationalLoungeAccess: "0" },
    { BREAK: "" },
    { education: "0%", multiplier: 0, cap: null },
    { fuel: "0%", multiplier: 0, cap: null },
    { jewellery: "0%", multiplier: 0, cap: null },
    { govtPayments: "0%", multiplier: 0, cap: null },
    { insurance: "0%", multiplier: 0 },
    { offlineSpends: "1.5%", multiplier: 0.015, cap: null },
    { onlineSpends: "1.5%", multiplier: 0.015, cap: null },
    { rent: "0%", multiplier: 0 },
    { utilities: "1.5%", multiplier: 0.015, cap: null },
    { wallet: "0%", multiplier: 0 },
    { BREAK: "" },
    { swiggy: "10%", multiplier: 0.1, cap: 1000, overflowMultiplier: 0.015 },
    { zomato: "10%", multiplier: 0.1, cap: 1000, overflowMultiplier: 0.015 },
    { uber: "1.5%", multiplier: 0.015, cap: null },
    { ola: "1.5%", multiplier: 0.015, cap: null },
    { amazon: "1.5%", multiplier: 0.015, cap: null },
    { flipkart: "1.5%", multiplier: 0.015, cap: null },
    { bestFor: "Online Spends" },
  ],
  hdfcMillennia: [
    { annualFees: "₹999" },
    { joiningBenefits: "" },
    { renewalBenefits: "" },
    { baseRewardRate: "5%" },
    { domesticLoungeAccess: "0" },
    { internationalLoungeAccess: "0" },
    { BREAK: "" },
    { education: "1%", multiplier: 0.01, cap: null },
    { fuel: "0%", multiplier: 0, cap: null },
    { jewellery: "1%", multiplier: 0.01, cap: null },
    { govtPayments: "0%", multiplier: 0, cap: null },
    { insurance: "1%", multiplier: 0.01 },
    { offlineSpends: "1%", multiplier: 0.01, cap: null },
    { onlineSpends: "1%", multiplier: 0.01, cap: null },
    { rent: "0%", multiplier: 0 },
    { utilities: "1%", multiplier: 0.01 },
    { wallet: "1%", multiplier: 0.01 },
    { BREAK: "" },
    { swiggy: "5%", multiplier: 0.05, cap: null },
    { zomato: "5%", multiplier: 0.05, cap: null },
    { uber: "5%", multiplier: 0.05, cap: null },
    { ola: "1%", multiplier: 0.01, cap: null },
    { amazon: "5%", multiplier: 0.05, cap: null },
    { flipkart: "5%", multiplier: 0.05, cap: null },
    { bestFor: "Online Spends" },
  ],
};

export const calculationRows = [
  {
    name: "Annual Fees",
    id: "annualFees",
    value: "",
    isNum: false,
  },
  {
    name: "Joining Benefits",
    id: "joiningBenefits",
    value: "",
    isNum: false,
  },
  {
    name: "Renewal Benefits",
    id: "renewalBenefits",
    value: "",
    isNum: false,
  },
  {
    name: "Base Reward Rate",
    id: "baseRewardRate",
    value: "",
    isNum: false,
  },
  {
    name: "Domestic Lounge Access",
    id: "domesticLoungeAccess",
    value: "",
    isNum: false,
  },
  {
    name: "International Lounge Access",
    id: "internationalLoungeAccess",
    value: "",
    isNum: false,
  },
  {
    name: "",
    id: "BREAK",
    value: "",
    isNum: false,
  },
  {
    name: "Education Expenses",
    id: "education",
    value: "",
    isNum: true,
  },
  {
    name: "Fuel Expenses",
    id: "fuel",
    value: "",
    isNum: true,
  },
  {
    name: "Jewellery Expenses",
    id: "jewellery",
    value: "",
    isNum: true,
  },
  {
    name: "Govt. Payments",
    id: "govtPayments",
    value: "",
    isNum: true,
  },
  {
    name: "Insurance",
    id: "insurance",
    value: "",
    isNum: true,
  },
  {
    name: "Offline Spends",
    id: "offlineSpends",
    value: "",
    isNum: true,
  },
  {
    name: "Online Spends",
    id: "onlineSpends",
    value: "",
    isNum: true,
  },
  {
    name: "Rent",
    id: "rent",
    value: "",
    isNum: true,
  },
  {
    name: "Utilities",
    id: "utilities",
    value: "",
    isNum: true,
  },
  {
    name: "Wallet Loads",
    id: "wallet",
    value: "",
    isNum: true,
  },
  {
    name: "",
    id: "BREAK",
    value: "",
    isNum: false,
  },
  {
    name: "Swiggy Expenses",
    id: "swiggy",
    value: "",
    isNum: true,
  },
  {
    name: "Zomato Expenses",
    id: "zomato",
    value: "",
    isNum: true,
  },
  {
    name: "Uber Expenses",
    id: "uber",
    value: "",
    isNum: true,
  },
  {
    name: "Ola Expenses",
    id: "ola",
    value: "",
    isNum: true,
  },
  {
    name: "Amazon Expenses",
    id: "amazon",
    value: "",
    isNum: true,
  },
  {
    name: "Flipkart Expenses",
    id: "flipkart",
    value: "",
    isNum: true,
  },
  {
    name: "Best For",
    id: "bestFor",
    value: "",
    isNum: false,
  },
];
